// <auto-generated />
using FirtsWebMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirtsWebMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231111025829_Create_table_HethongPhanPhoi")]
    partial class Create_table_HethongPhanPhoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FirtsWebMVC.Models.HeThongPhanPhoi", b =>
                {
                    b.Property<string>("MaHTTP")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHTTP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHTTP");

                    b.ToTable("HeThongPhanPhoi");
                });

            modelBuilder.Entity("FirtsWebMVC.Models.Person", b =>
                {
                    b.Property<string>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Person");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FirtsWebMVC.Models.Employee", b =>
                {
                    b.HasBaseType("FirtsWebMVC.Models.Person");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FirtsWebMVC.Models.Employee", b =>
                {
                    b.HasOne("FirtsWebMVC.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("FirtsWebMVC.Models.Employee", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
